import Head from "next/head";
import AddCadidateForm from "../src/main/ui/components/AddCadidateForm";
import Header from "../src/main/ui/components/Header";

export default function AddCandidatePage() {
  return (
    <div>
      <Head>
        <title>Add Candidate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header currentPage="Add Candidate" />

      <main>
        <AddCadidateForm />
      </main>
    </div>
  );
}
