import Head from "next/head";
import CandidateList from "../src/main/ui/components/CandidateList";
import Header from "../src/main/ui/components/Header";
export default function CandidateListPage({ candidates }) {
  return (
    <div>
      <Head>
        <title>Candidate List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header currentPage="Candidate List" />

      <main>
        <CandidateList candidates={candidates} />
      </main>
    </div>
  );
}

CandidateListPage.getInitialProps = async (ctx) => {
  const res = await fetch("http://localhost:3000/api/getAllCandidates");
  const canndidatesJson = await res.json();
  return { candidates: canndidatesJson };
};
